[surrogate_args]
pyrfr_wrapper = "target_algorithms/surrogate/cplex_regions200/pyrfr_wrapper.cplex_regions200.par10.random.pkl"
pyrfr_model = "target_algorithms/surrogate/cplex_regions200/pyrfr_model.cplex_regions200.par10.random.bin"
config_space = "target_algorithms/surrogate/cplex_regions200/config_space.cplex_regions200.par10.random.pcs"
inst_feat_dict = "target_algorithms/surrogate/cplex_regions200/inst_feat_dict.cplex_regions200.par10.random.json"

[irace_args]
parameter_file = "target_instances/surrogate/cplex_regions200/config_space.cplex_regions200.par10.random.irace.txt"
train_instances_file = "target_instances/surrogate/cplex_regions200/train-1.txt"
test_instances_file = "target_instances/surrogate/cplex_regions200/test-1.txt"
digits = 10
max_experiments = 2000
is_cost = true # Otherwise it is time
