[surrogate_args]
pyrfr_wrapper = "target_algorithms/surrogate/minisat_randomk3/pyrfr_wrapper.minisat_randomk3.par10.random.pkl"
pyrfr_model = "target_algorithms/surrogate/minisat_randomk3/pyrfr_model.minisat_randomk3.par10.random.bin"
config_space = "target_algorithms/surrogate/minisat_randomk3/config_space.minisat_randomk3.par10.random.pcs"
inst_feat_dict = "target_algorithms/surrogate/minisat_randomk3/inst_feat_dict.minisat_randomk3.par10.random.json"

[irace_args]
parameter_file = "target_instances/surrogate/minisat_randomk3/config_space.minisat_randomk3.par10.random.irace.txt"
train_instances_file = "target_instances/surrogate/minisat_randomk3/train-1.txt"
test_instances_file = "target_instances/surrogate/minisat_randomk3/test-1.txt"
digits = 10
max_experiments = 2000
is_cost = false # Otherwise it is time
